apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.network/backend: "true"
    io.kompose.network/catalogdomain: "true"
    io.kompose.service: otasoft-catalog
  name: otasoft-catalog
spec:
  containers:
    - env:
        - name: ELASTICSEARCH_CLUSTER_NAME
        - name: ELASTICSEARCH_HOST
        - name: ELASTICSEARCH_NETWORK_HOST
        - name: ELASTICSEARCH_NODE
        - name: ELASTICSEARCH_PASSWORD
        - name: ELASTICSEARCH_PORT
        - name: ELASTICSEARCH_USERNAME
        - name: KIBANA_PORT
        - name: KIBANA_SERVER_NAME
        - name: MASTER_DATABASE
        - name: MASTER_HOST
          value: otasoft-catalog-mysql-master
        - name: MASTER_PASSWORD
        - name: MASTER_PORT
          value: "3306"
        - name: MASTER_USER
        - name: MYSQL_MASTER_ROOT_PASSWORD
        - name: MYSQL_REPLICATION_PASSWORD
        - name: MYSQL_REPLICATION_USER
        - name: MYSQL_SLAVE_ROOT_PASSWORD
        - name: PROXY_BASIC_AUTH_PASSWORD
        - name: PROXY_BASIC_AUTH_USERNAME
        - name: RABBITMQ_DEFAULT_PASS
        - name: RABBITMQ_DEFAULT_USER
        - name: RABBITMQ_DEFAULT_VHOST
        - name: RABBITMQ_FIRST_HOST_PORT
          value: "5672"
        - name: RABBITMQ_NODENAME
          value: otasoft-api-rabbitmq
        - name: SLAVE_DATABASE
        - name: SLAVE_HOST
          value: otasoft-catalog-mysql-slave
        - name: SLAVE_PASSWORD
        - name: SLAVE_PORT
        - name: SLAVE_USER
      image: otasoft-catalog:dev
      name: otasoft-catalog
      resources: {}
  restartPolicy: OnFailure
status: {}
