apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: otasoft-catalog-es02
  name: otasoft-catalog-es02
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: otasoft-catalog-es02
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/catalogdomain: "true"
        io.kompose.network/otasoft-catalog-elastic: "true"
        io.kompose.service: otasoft-catalog-es02
    spec:
      containers:
        - env:
            - name: ELASTIC_PASSWORD
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: bootstrap.memory_lock
              value: "true"
            - name: cluster.initial_master_nodes
              value: otasoft-catalog-es01,otasoft-catalog-es02,otasoft-catalog-es03
            - name: cluster.name
            - name: discovery.seed_hosts
              value: otasoft-catalog-es01,otasoft-catalog-es03
            - name: http.port
            - name: network.host
            - name: node.name
              value: otasoft-catalog-es02
          image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
          name: otasoft-catalog-es02
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: otasoft-catalog-es-data02
      restartPolicy: Always
      volumes:
        - name: otasoft-catalog-es-data02
          persistentVolumeClaim:
            claimName: otasoft-catalog-es-data02
status: {}
