apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: otasoft-catalog-kibana
  name: otasoft-catalog-kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: otasoft-catalog-kibana
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/catalogdomain: "true"
        io.kompose.network/otasoft-catalog-elastic: "true"
        io.kompose.network/otasoft-catalog-proxy: "true"
        io.kompose.service: otasoft-catalog-kibana
    spec:
      containers:
        - env:
            - name: ELASTICSEARCH_HOSTS
              value: 'http://otasoft-catalog-elasticsearch:'
            - name: SERVER_NAME
          image: docker.elastic.co/kibana/kibana:7.9.2
          name: otasoft-catalog-kibana
          ports:
            - containerPort: 5601
          resources: {}
      restartPolicy: Always
status: {}
