apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.network/customerdomain: "true"
    io.kompose.service: otasoft-customer-db
  name: otasoft-customer-db
spec:
  containers:
    - env:
        - name: POSTGRES_DB
        - name: POSTGRES_PASSWORD
        - name: POSTGRES_USER
      image: postgres:13-alpine
      name: otasoft-customer-db
      ports:
        - containerPort: 5432
      resources: {}
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: customerdata
  restartPolicy: OnFailure
  volumes:
    - name: customerdata
      persistentVolumeClaim:
        claimName: customerdata
status: {}
