apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.network/backend: "true"
    io.kompose.network/customerdomain: "true"
    io.kompose.service: otasoft-customer
  name: otasoft-customer
spec:
  containers:
    - env:
        - name: POSTGRES_DATABASE
        - name: POSTGRES_HOST
          value: otasoft-customer-db
        - name: POSTGRES_PASSWORD
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USERNAME
        - name: RABBITMQ_DEFAULT_PASS
        - name: RABBITMQ_DEFAULT_USER
        - name: RABBITMQ_DEFAULT_VHOST
        - name: RABBITMQ_FIRST_HOST_PORT
          value: "5672"
        - name: RABBITMQ_NODENAME
          value: otasoft-api-rabbitmq
      image: otasoft-customer:dev
      name: otasoft-customer
      resources: {}
  restartPolicy: OnFailure
status: {}
